version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: videoglaz
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/videoglaz
      SECRET_KEY: change-me-in-production
    depends_on:
      - db
    volumes:
      - ./:/app

volumes:
  postgres_data: